version: '3'

services:

  db:
    image: postgres
    container_name: pdl_pgdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: pduser
      POSTGRES_PASSWORD: keyfordb
      POSTGRES_DB: propyth
      PGDATA: /tmp
    volumes:
      - ./dbdata/postgres:/var/lib/postgresql/data

  web:
    build: ./docker/python
    container_name: pdl_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./source/:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: pdl_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-foobar}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    ports:
    - "8009:80"
    volumes:
    - my-data:/var/lib/pgadmin

volumes:
  my-data: